TEMPLATES_AUTO_RELOAD = True
#DEBUG = True
#ENV = 'development'
MYSQL_DATABASE_HOST = "localhost"
MYSQL_DATABSE_PORT = 3306
MYSQL_DATABASE_USER = 'root'
MYSQL_DATABSE_PASSWORD = ''
MYSQL_DATABASE_DB = 'randomusic'
