TEMPLATES_AUTO_RELOAD = True
#DEBUG = True
#ENV = 'development'
MYSQL_DATABASE_HOST = 'process.env.DB_HOST'
MYSQL_DATABSE_PORT = 3309
MYSQL_DATABASE_USER = 'root'
MYSQL_DATABSE_PASSWORD = 'root'
MYSQL_DATABASE_DB = 'randomusic'
